version: '3.8'
services:
  db:
    image: postgres:13
    container_name: taksmanager-DB
    environment:
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: taksmanagerDB
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db-data: